class AddSquaresToPuzzles < ActiveRecord::Migration
  def change

    add_column :puzzles, :"0, 0", :string
    add_column :puzzles, :"0, 1", :string
    add_column :puzzles, :"0, 2", :string
    add_column :puzzles, :"0, 3", :string
    add_column :puzzles, :"0, 4", :string
    add_column :puzzles, :"0, 5", :string
    add_column :puzzles, :"0, 6", :string
    add_column :puzzles, :"0, 7", :string
    add_column :puzzles, :"0, 8", :string
    add_column :puzzles, :"1, 0", :string
    add_column :puzzles, :"1, 1", :string
    add_column :puzzles, :"1, 2", :string
    add_column :puzzles, :"1, 3", :string
    add_column :puzzles, :"1, 4", :string
    add_column :puzzles, :"1, 5", :string
    add_column :puzzles, :"1, 6", :string
    add_column :puzzles, :"1, 7", :string
    add_column :puzzles, :"1, 8", :string
    add_column :puzzles, :"2, 0", :string
    add_column :puzzles, :"2, 1", :string
    add_column :puzzles, :"2, 2", :string
    add_column :puzzles, :"2, 3", :string
    add_column :puzzles, :"2, 4", :string
    add_column :puzzles, :"2, 5", :string
    add_column :puzzles, :"2, 6", :string
    add_column :puzzles, :"2, 7", :string
    add_column :puzzles, :"2, 8", :string
    add_column :puzzles, :"3, 0", :string
    add_column :puzzles, :"3, 1", :string
    add_column :puzzles, :"3, 2", :string
    add_column :puzzles, :"3, 3", :string
    add_column :puzzles, :"3, 4", :string
    add_column :puzzles, :"3, 5", :string
    add_column :puzzles, :"3, 6", :string
    add_column :puzzles, :"3, 7", :string
    add_column :puzzles, :"3, 8", :string
    add_column :puzzles, :"4, 0", :string
    add_column :puzzles, :"4, 1", :string
    add_column :puzzles, :"4, 2", :string
    add_column :puzzles, :"4, 3", :string
    add_column :puzzles, :"4, 4", :string
    add_column :puzzles, :"4, 5", :string
    add_column :puzzles, :"4, 6", :string
    add_column :puzzles, :"4, 7", :string
    add_column :puzzles, :"4, 8", :string
    add_column :puzzles, :"5, 0", :string
    add_column :puzzles, :"5, 1", :string
    add_column :puzzles, :"5, 2", :string
    add_column :puzzles, :"5, 3", :string
    add_column :puzzles, :"5, 4", :string
    add_column :puzzles, :"5, 5", :string
    add_column :puzzles, :"5, 6", :string
    add_column :puzzles, :"5, 7", :string
    add_column :puzzles, :"5, 8", :string
    add_column :puzzles, :"6, 0", :string
    add_column :puzzles, :"6, 1", :string
    add_column :puzzles, :"6, 2", :string
    add_column :puzzles, :"6, 3", :string
    add_column :puzzles, :"6, 4", :string
    add_column :puzzles, :"6, 5", :string
    add_column :puzzles, :"6, 6", :string
    add_column :puzzles, :"6, 7", :string
    add_column :puzzles, :"6, 8", :string
    add_column :puzzles, :"7, 0", :string
    add_column :puzzles, :"7, 1", :string
    add_column :puzzles, :"7, 2", :string
    add_column :puzzles, :"7, 3", :string
    add_column :puzzles, :"7, 4", :string
    add_column :puzzles, :"7, 5", :string
    add_column :puzzles, :"7, 6", :string
    add_column :puzzles, :"7, 7", :string
    add_column :puzzles, :"7, 8", :string
    add_column :puzzles, :"8, 0", :string
    add_column :puzzles, :"8, 1", :string
    add_column :puzzles, :"8, 2", :string
    add_column :puzzles, :"8, 3", :string
    add_column :puzzles, :"8, 4", :string
    add_column :puzzles, :"8, 5", :string
    add_column :puzzles, :"8, 6", :string
    add_column :puzzles, :"8, 7", :string
    add_column :puzzles, :"8, 8", :string
  end
end
